"""baseline schema

Revision ID: 5e0c7a18c5fa
Revises: 
Create Date: 2026-06-10 16:22:22.183907
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e0c7a18c5fa'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('affiliate_groups',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('guest_id', sa.Uuid(), nullable=False),
    sa.Column('kakao_id', sa.String(length=100), nullable=True),
    sa.Column('nickname', sa.String(length=50), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('fcm_token', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guest_id'),
    sa.UniqueConstraint('kakao_id')
    )
    op.create_table('stores',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_phone', sa.String(length=20), nullable=False),
    sa.Column('store_name', sa.String(length=100), nullable=False),
    sa.Column('stamp_goal', sa.Integer(), nullable=False),
    sa.Column('reward_price_krw', sa.Integer(), nullable=False),
    sa.Column('reward_description', sa.Text(), nullable=False),
    sa.Column('coupon_image_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_phone')
    )
    op.create_table('affiliate_members',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('group_id', sa.Uuid(), nullable=False),
    sa.Column('store_id', sa.Uuid(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['affiliate_groups.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'store_id', name='uq_group_store')
    )
    op.create_table('agent_action_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('store_id', sa.Uuid(), nullable=False),
    sa.Column('target_customer_id', sa.Uuid(), nullable=False),
    sa.Column('segment', sa.String(length=20), nullable=False),
    sa.Column('action_type', sa.String(length=30), nullable=False, comment='comeback_stamp | near_reward_push | ...'),
    sa.Column('cost_stamps', sa.Integer(), nullable=False),
    sa.Column('is_holdout', sa.Boolean(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.ForeignKeyConstraint(['target_customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_policies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('store_id', sa.Uuid(), nullable=False),
    sa.Column('budget_stamps_max', sa.Integer(), nullable=False),
    sa.Column('budget_consumed', sa.Integer(), nullable=False),
    sa.Column('budget_period', sa.String(length=7), nullable=True),
    sa.Column('automation_mode', sa.String(length=20), nullable=False),
    sa.Column('at_risk_days', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id')
    )
    op.create_table('co_stamp_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('group_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('required_visits', sa.Integer(), nullable=False),
    sa.Column('reward_store_id', sa.Uuid(), nullable=False),
    sa.Column('reward_description', sa.Text(), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['affiliate_groups.id'], ),
    sa.ForeignKeyConstraint(['reward_store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cross_promos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('group_id', sa.Uuid(), nullable=False),
    sa.Column('store_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('bonus_stamps', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['affiliate_groups.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('marketplace_listings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('seller_customer_id', sa.Uuid(), nullable=False),
    sa.Column('store_id', sa.Uuid(), nullable=False),
    sa.Column('stamp_qty', sa.Integer(), nullable=False),
    sa.Column('unit_face_value_krw', sa.Integer(), nullable=False),
    sa.Column('ask_price_krw', sa.Integer(), nullable=False, comment='매물 총 호가(머니). 액면가 합 이하 강제.'),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('buyer_customer_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('sold_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('ask_price_krw <= unit_face_value_krw * stamp_qty', name='ck_listing_ask_below_face'),
    sa.CheckConstraint('ask_price_krw > 0', name='ck_listing_ask_positive'),
    sa.CheckConstraint('stamp_qty > 0', name='ck_listing_qty_positive'),
    sa.ForeignKeyConstraint(['buyer_customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['seller_customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('money_accounts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('balance_krw', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('balance_krw >= 0', name='ck_money_balance_nonneg'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_id')
    )
    op.create_table('stamp_cards',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('store_id', sa.Uuid(), nullable=False),
    sa.Column('current_stamps', sa.Integer(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('store_payables',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('store_id', sa.Uuid(), nullable=False),
    sa.Column('amount_krw', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('settled_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('co_stamp_claims',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('coupon_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['co_stamp_events.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'customer_id', name='uq_event_customer')
    )
    op.create_table('coupons',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('stamp_card_id', sa.Uuid(), nullable=False),
    sa.Column('face_value_krw', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['stamp_card_id'], ['stamp_cards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('money_transactions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('txn_type', sa.String(length=30), nullable=False),
    sa.Column('amount_krw', sa.Integer(), nullable=False, comment='부호 있음: 충전/판매 +, 구매 -'),
    sa.Column('balance_after', sa.Integer(), nullable=False),
    sa.Column('ref_type', sa.String(length=30), nullable=True),
    sa.Column('ref_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['money_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('visits',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('stamp_card_id', sa.Uuid(), nullable=False),
    sa.Column('stamped_by', sa.Uuid(), nullable=False, comment='Store owner ID who scanned'),
    sa.Column('stamped_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['stamp_card_id'], ['stamp_cards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('visits')
    op.drop_table('money_transactions')
    op.drop_table('coupons')
    op.drop_table('co_stamp_claims')
    op.drop_table('store_payables')
    op.drop_table('stamp_cards')
    op.drop_table('money_accounts')
    op.drop_table('marketplace_listings')
    op.drop_table('cross_promos')
    op.drop_table('co_stamp_events')
    op.drop_table('agent_policies')
    op.drop_table('agent_action_logs')
    op.drop_table('affiliate_members')
    op.drop_table('stores')
    op.drop_table('customers')
    op.drop_table('affiliate_groups')
    # ### end Alembic commands ###
